export default {
  login: "SarwarAhmad7",
  id: 68182571,
  node_id: "MDQ6VXNlcjY4MTgyNTcx",
  avatar_url: "https://avatars.githubusercontent.com/u/68182571?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/SarwarAhmad7",
  html_url: "https://github.com/SarwarAhmad7",
  followers_url: "https://api.github.com/users/SarwarAhmad7/followers",
  following_url:
    "https://api.github.com/users/SarwarAhmad7/following{/other_user}",
  gists_url: "https://api.github.com/users/SarwarAhmad7/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/SarwarAhmad7/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/SarwarAhmad7/subscriptions",
  organizations_url: "https://api.github.com/users/SarwarAhmad7/orgs",
  repos_url: "https://api.github.com/users/SarwarAhmad7/repos",
  events_url: "https://api.github.com/users/SarwarAhmad7/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/SarwarAhmad7/received_events",
  type: "User",
  user_view_type: "public",
  site_admin: false,
  name: "Sarwar Ahmad",
  company: null,
  blog: "",
  location: "Srinagar, Jammu and Kashmir",
  email: null,
  hireable: null,
  bio: "Data wrangler | Code enthusiast\r\nReact ⚛️ • Python 🐍 • Big Data 📡\r\nAlways building. Always learning.",
  twitter_username: null,
  public_repos: 9,
  public_gists: 0,
  followers: 0,
  following: 4,
  created_at: "2020-07-12T08:48:43Z",
  updated_at: "2025-04-24T17:53:57Z",
};
